// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need session-level advisory locks, which Supabase's
    // transaction pooler (port 6543) doesn't support. DIRECT_URL points at the
    // session pooler (5432) for that; DATABASE_URL stays the runtime
    // connection. Locally the two are the same, so fall back.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
