// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// An env var set to an empty string (`DIRECT_URL=` in a .env, or a blank
// value in Vercel) is still defined, so `??` would pick it and hand the CLI an
// empty URL. Treat blank as unset.
const present = (value: string | undefined) => value?.trim() || undefined;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need session-level advisory locks, which Supabase's
    // transaction pooler (port 6543) doesn't support. DIRECT_URL points at the
    // session pooler (5432) for that; DATABASE_URL stays the runtime
    // connection. Locally the two are the same, so fall back.
    url: present(process.env["DIRECT_URL"]) ?? present(process.env["DATABASE_URL"]),
  },
});
